version: '2.2'
services:
  webapi:
    build: .
    container_name: api
    ports: 
      - "8888:8888"
  #   depends_on:
  #     - redis
  # redis:
  #   restart: always
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   # expose:
  #   #   - "6379"
  #   volumes:
  #     - /data/redis-data:/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 33060:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    
